/*
    ⚠ BEHOLD, THE RESULT OF TENS OF HOURS OF TESTING AND RESEARCH ⚠

    Building this code was not easy, took me many days of testing and research to get it right.
    Althought still not perfect, I believe this code is the best way to clean up player names.
    In general:
    - It removes spammy characters, like character repetitions and zalgo text
    - Does that without breaking scripts like hebreu and thai (or just a tiny bit)
    - It respects up to a single invisible character in the string, no matter which one
    - It does not break emoji variants that end up with 0xFE0E/0xFE0F
    - It does not break up any emoji, actually. THe only broken ones you will see are the ones that
        are already broken (likely due to missing 0xFE0E/0xFE0F)
    - It splits characters into valid Unicode CodePoints instead of UTF16 codepoints
    - All names are trimmed to 36 Unicode characters AFTER ALL THE CLEANING, which is a very
        generous limit and only affects about 0.1% of of all names (usually the spammy ones)
    - If the name is empty after any cleaning step, it will return a hex representation of the
        original name, prefixed with ∅, and that allows for it to be searched char-by-char
    - Removes all prefix invisible characters, or Nonspacing_Mark (diacritics) at the beginning
    - It should be impossible to have an invisible/empty name right now.
    - The code is not particularly optimized for performance, but should still clean up 1000 names
        in under a millisecond, which is more than enough for any use case.

    RESEARCH REFERENCES:
        https://unicode.org/Public/15.1.0/ucd/emoji/emoji-variation-sequences.txt
        https://unicode.org/Public/15.1.0/ucd/emoji/emoji-data.txt
        https://unicode.org/Public/emoji/latest/emoji-test.txt
        https://unicode.org/Public/emoji/latest/emoji-sequences.txt
        https://v8.dev/features/regexp-v-flag
        https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets
        https://www.unicode.org/Public/UCD/latest/ucd/PropList.txt
*/

/**
 * Set of invisible characters generated by https://github.com/hediet/vscode-unicode-data
 * This also includes some characters that are removed prior to this step, namely:
 *  C0 controls, C1 controls, RTL marks, and RTL overrides
 */
const invisibleChars = new Set([
    0x0009, 0x000a, 0x000b, 0x000c, 0x000d, 0x0020, 0x007f, 0x00a0, 0x00ad, 0x034f, 0x061c, 0x115f, 0x1160, 0x17b4,
    0x17b5, 0x180b, 0x180c, 0x180d, 0x180e, 0x1cbb, 0x1cbc, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006,
    0x2007, 0x2008, 0x2009, 0x200a, 0x200b, 0x200c, 0x200d, 0x200e, 0x200f, 0x202a, 0x202b, 0x202c, 0x202d, 0x202e,
    0x202f, 0x205f, 0x2060, 0x2061, 0x2062, 0x2063, 0x2064, 0x2065, 0x2066, 0x2067, 0x2068, 0x2069, 0x206a, 0x206b,
    0x206c, 0x206d, 0x206e, 0x206f, 0x2800, 0x3000, 0x3164, 0xfe00, 0xfe01, 0xfe02, 0xfe03, 0xfe04, 0xfe05, 0xfe06,
    0xfe07, 0xfe08, 0xfe09, 0xfe0a, 0xfe0b, 0xfe0c, 0xfe0d, 0xfe0e, 0xfe0f, 0xfeff, 0xffa0, 0xfff0, 0xfff1, 0xfff2,
    0xfff3, 0xfff4, 0xfff5, 0xfff6, 0xfff7, 0xfff8, 0xfffc, 0x133fc, 0x1d173, 0x1d174, 0x1d175, 0x1d176, 0x1d177,
    0x1d178, 0x1d179, 0x1d17a, 0xe0000, 0xe0001, 0xe0002, 0xe0003, 0xe0004, 0xe0005, 0xe0006, 0xe0007, 0xe0008, 0xe0009,
    0xe000a, 0xe000b, 0xe000c, 0xe000d, 0xe000e, 0xe000f, 0xe0010, 0xe0011, 0xe0012, 0xe0013, 0xe0014, 0xe0015, 0xe0016,
    0xe0017, 0xe0018, 0xe0019, 0xe001a, 0xe001b, 0xe001c, 0xe001d, 0xe001e, 0xe001f, 0xe0020, 0xe0021, 0xe0022, 0xe0023,
    0xe0024, 0xe0025, 0xe0026, 0xe0027, 0xe0028, 0xe0029, 0xe002a, 0xe002b, 0xe002c, 0xe002d, 0xe002e, 0xe002f, 0xe0030,
    0xe0031, 0xe0032, 0xe0033, 0xe0034, 0xe0035, 0xe0036, 0xe0037, 0xe0038, 0xe0039, 0xe003a, 0xe003b, 0xe003c, 0xe003d,
    0xe003e, 0xe003f, 0xe0040, 0xe0041, 0xe0042, 0xe0043, 0xe0044, 0xe0045, 0xe0046, 0xe0047, 0xe0048, 0xe0049, 0xe004a,
    0xe004b, 0xe004c, 0xe004d, 0xe004e, 0xe004f, 0xe0050, 0xe0051, 0xe0052, 0xe0053, 0xe0054, 0xe0055, 0xe0056, 0xe0057,
    0xe0058, 0xe0059, 0xe005a, 0xe005b, 0xe005c, 0xe005d, 0xe005e, 0xe005f, 0xe0060, 0xe0061, 0xe0062, 0xe0063, 0xe0064,
    0xe0065, 0xe0066, 0xe0067, 0xe0068, 0xe0069, 0xe006a, 0xe006b, 0xe006c, 0xe006d, 0xe006e, 0xe006f, 0xe0070, 0xe0071,
    0xe0072, 0xe0073, 0xe0074, 0xe0075, 0xe0076, 0xe0077, 0xe0078, 0xe0079, 0xe007a, 0xe007b, 0xe007c, 0xe007d, 0xe007e,
    0xe007f, 0xe0100, 0xe0101, 0xe0102, 0xe0103, 0xe0104, 0xe0105, 0xe0106, 0xe0107, 0xe0108, 0xe0109, 0xe010a, 0xe010b,
    0xe010c, 0xe010d, 0xe010e, 0xe010f, 0xe0110, 0xe0111, 0xe0112, 0xe0113, 0xe0114, 0xe0115, 0xe0116, 0xe0117, 0xe0118,
    0xe0119, 0xe011a, 0xe011b, 0xe011c, 0xe011d, 0xe011e, 0xe011f, 0xe0120, 0xe0121, 0xe0122, 0xe0123, 0xe0124, 0xe0125,
    0xe0126, 0xe0127, 0xe0128, 0xe0129, 0xe012a, 0xe012b, 0xe012c, 0xe012d, 0xe012e, 0xe012f, 0xe0130, 0xe0131, 0xe0132,
    0xe0133, 0xe0134, 0xe0135, 0xe0136, 0xe0137, 0xe0138, 0xe0139, 0xe013a, 0xe013b, 0xe013c, 0xe013d, 0xe013e, 0xe013f,
    0xe0140, 0xe0141, 0xe0142, 0xe0143, 0xe0144, 0xe0145, 0xe0146, 0xe0147, 0xe0148, 0xe0149, 0xe014a, 0xe014b, 0xe014c,
    0xe014d, 0xe014e, 0xe014f, 0xe0150, 0xe0151, 0xe0152, 0xe0153, 0xe0154, 0xe0155, 0xe0156, 0xe0157, 0xe0158, 0xe0159,
    0xe015a, 0xe015b, 0xe015c, 0xe015d, 0xe015e, 0xe015f, 0xe0160, 0xe0161, 0xe0162, 0xe0163, 0xe0164, 0xe0165, 0xe0166,
    0xe0167, 0xe0168, 0xe0169, 0xe016a, 0xe016b, 0xe016c, 0xe016d, 0xe016e, 0xe016f, 0xe0170, 0xe0171, 0xe0172, 0xe0173,
    0xe0174, 0xe0175, 0xe0176, 0xe0177, 0xe0178, 0xe0179, 0xe017a, 0xe017b, 0xe017c, 0xe017d, 0xe017e, 0xe017f, 0xe0180,
    0xe0181, 0xe0182, 0xe0183, 0xe0184, 0xe0185, 0xe0186, 0xe0187, 0xe0188, 0xe0189, 0xe018a, 0xe018b, 0xe018c, 0xe018d,
    0xe018e, 0xe018f, 0xe0190, 0xe0191, 0xe0192, 0xe0193, 0xe0194, 0xe0195, 0xe0196, 0xe0197, 0xe0198, 0xe0199, 0xe019a,
    0xe019b, 0xe019c, 0xe019d, 0xe019e, 0xe019f, 0xe01a0, 0xe01a1, 0xe01a2, 0xe01a3, 0xe01a4, 0xe01a5, 0xe01a6, 0xe01a7,
    0xe01a8, 0xe01a9, 0xe01aa, 0xe01ab, 0xe01ac, 0xe01ad, 0xe01ae, 0xe01af, 0xe01b0, 0xe01b1, 0xe01b2, 0xe01b3, 0xe01b4,
    0xe01b5, 0xe01b6, 0xe01b7, 0xe01b8, 0xe01b9, 0xe01ba, 0xe01bb, 0xe01bc, 0xe01bd, 0xe01be, 0xe01bf, 0xe01c0, 0xe01c1,
    0xe01c2, 0xe01c3, 0xe01c4, 0xe01c5, 0xe01c6, 0xe01c7, 0xe01c8, 0xe01c9, 0xe01ca, 0xe01cb, 0xe01cc, 0xe01cd, 0xe01ce,
    0xe01cf, 0xe01d0, 0xe01d1, 0xe01d2, 0xe01d3, 0xe01d4, 0xe01d5, 0xe01d6, 0xe01d7, 0xe01d8, 0xe01d9, 0xe01da, 0xe01db,
    0xe01dc, 0xe01dd, 0xe01de, 0xe01df, 0xe01e0, 0xe01e1, 0xe01e2, 0xe01e3, 0xe01e4, 0xe01e5, 0xe01e6, 0xe01e7, 0xe01e8,
    0xe01e9, 0xe01ea, 0xe01eb, 0xe01ec, 0xe01ed, 0xe01ee, 0xe01ef,
]);

/**
 * Converts a string to a hex array of its characters.
 * Default limit of 35 characters to account for the ∅
 */
const hexInvalidString = (str: string, limit = 35) => {
    const hexArr = [...str].map((c) => (c.codePointAt(0) ?? 0x00).toString(16));
    const outArr: string[] = [];
    let charCountWithSpace = 0;
    for (let i = 0; i < hexArr.length; i++) {
        if (outArr.includes(hexArr[i])) continue;
        if (charCountWithSpace + hexArr[i].length > limit) break;
        outArr.push(hexArr[i]);
        charCountWithSpace += hexArr[i].length + 1; //account for space
    }
    return outArr;
};

/**
 * Checks if a character is an emoji using the native RGI_Emoji regex property.
 * Uses the 'v' flag (Node 22+ / Chrome 112+) when available, otherwise falls back
 * to the 'u' flag with Extended_Pictographic (Chrome 103+).
 */
let emojiRegex: RegExp;
try {
    emojiRegex = new RegExp('^\\p{RGI_Emoji}$', 'v');
} catch {
    emojiRegex = new RegExp('^\\p{Extended_Pictographic}$', 'u');
}
const isEmoji = (char: string) => {
    return emojiRegex.test(char);
};

/**
 * Objectives:
 * - remove leading invisible characters
 * - remove over 3 repeated chars
 * - remove any repeated invisible chars
 * - only allow a single trailing codepoint if it's 0xFE0E/0xFE0F and the previous char is an emoji
 * NOTE: need to use [...str] to split the string into unicode codepoints, otherwise they become UTF8 codepoints
 */
const cleanTrimCodePoints = (str: string, lenLimit = 36) => {
    let out = '';
    let lastChar = '';
    let lastCharCount = 0;
    let pendingInvisibleChar = '';
    let totalCodePoints = 0;
    const chars = [...str]; //do not use .split('')
    for (let i = 0; i < chars.length; i++) {
        //ensure size limit
        //NOTE: only about 0.1% of names are longer than 36 chars after cleaning
        if (totalCodePoints >= lenLimit) break;

        //remove leading invisible characters
        const currChar = chars[i];
        const currCharCodePoint = currChar.codePointAt(0)!;
        const isCharInvible = invisibleChars.has(currCharCodePoint);
        if (!out.length && isCharInvible) continue;

        //remove repeated chars
        const isCharRepeated = currChar === lastChar;
        if (isCharRepeated && lastCharCount >= (isCharInvible ? 1 : 3)) {
            continue;
        }

        //deal with trailing invisible chars
        let isCurrentPending = false;
        if (isCharInvible) {
            //if it's 0xFE0E/0xFE0F and the previous char is an emoji, don't hold it back
            const isVariationSelector =
                (currCharCodePoint === 0xfe0e || currCharCodePoint === 0xfe0f) && isEmoji(lastChar);
            if (!isVariationSelector) {
                //keep only the first pending
                if (!pendingInvisibleChar) {
                    pendingInvisibleChar = currChar;
                    isCurrentPending = true;
                }
                continue;
            }
        }
        if (!isCurrentPending && pendingInvisibleChar) {
            if (totalCodePoints >= lenLimit - 1) break;
            out += pendingInvisibleChar;
            totalCodePoints++;
            pendingInvisibleChar = '';
        }

        //append char
        lastChar = currChar;
        lastCharCount = isCharRepeated ? lastCharCount + 1 : 1;
        out += currChar;
        totalCodePoints++;
    }

    return out;
};

// Types
type TransformStep = (input: string) => string;
type CleanPlayerNameResult = {
    displayName: string;
    displayNameEmpty: boolean;
    pureName: string;
    pureNameEmpty: boolean;
};

// Constants
const EMPTY_SET = String.fromCodePoint(0x2205, 0x200b); // ∅

/**
 * Cleans up a player name and returns one version to be displayed, and one pure version to be used for fuzzy matching.
 * If the name does not contain any valid characters, it will return a searchable hex representation of the name.
 */
export default (originalName: string): CleanPlayerNameResult => {
    if (!originalName) {
        return {
            displayName: EMPTY_SET + 'EMPTY NAME',
            displayNameEmpty: true,
            pureName: 'emptyname',
            pureNameEmpty: true,
        };
    }

    //Order of operations:
    // 1. operations that remove the match completely
    // 2. operations that reduce the name
    // 3. finalization
    const displaySteps: TransformStep[] = [
        //should have been truncated by lua, but double checking due to the risk of DoS
        (x) => x.substring(0, 128),

        // https://docs.fivem.net/docs/game-references/text-formatting/
        // NOTE: never seen these being used: nrt|EX_R\*|BLIP_\S+|ACCEPT|CANCEL|PAD_\S+|INPUT_\S+|INPUTGROUP_\S+
        (x) =>
            x.replace(
                /~(HUD_\S+|HC_\S+|[a-z]|[a1]_\d+|bold|italic|ws|wanted_star|nrt|EX_R\*|BLIP_\S+|ACCEPT|CANCEL|PAD_\S+|INPUT_\S+|INPUTGROUP_\S+)~/gi,
                '',
            ),

        // console & chat color codes
        (x) => x.replace(/\^\d/gi, ''),

        // C0 controls + delete + C1 controls
        // \u200E               RTL mark
        // \u2067               RTL override
        (x) => x.replace(/[\p{Control}\u200E\u2067]/gu, ''),

        // \uA980-\uA9DF        javanese (oversized)
        // \u239B-\u23AD        Miscellaneous Technical — Bracket pieces items (oversized)
        // \u534D\u5350         swastika
        // \u1000-\u109F        Myanmar
        // \u0B80-\u0BFF        Tamil
        // \uFDFD\u2E3B         oversized characters
        (x) => x.replace(/[\uA980-\uA9DF\u239B-\u23AD\u534D\u5350\u1000-\u109F\u0B80-\u0BFF\uFDFD\u2E3B]/gu, ''),

        // UTF-16 ranges
        // U+12000 - U+123FF 	Cuneiform
        // U+12400 - U+1247F 	Cuneiform Numbers and Punctuation
        // U+12480 - U+1254F 	Early Dynastic Cuneiform
        // U+1D000 - U+1D0FF 	Byzantine Musical Symbols
        (x) => x.replace(/[\u{12000}-\u{123FF}\u{12400}-\u{1247F}\u{12480}-\u{1254F}\u{1D000}-\u{1D0FF}]/gu, ''),

        //2+ consecutive marks (zalgo text)
        (x) =>
            x.replace(/(^\p{Nonspacing_Mark}+)|(\p{Nonspacing_Mark}{3,})/gu, (match, leading, repeating) => {
                if (leading) return ''; // Remove leading non-spacing marks
                if (repeating) return repeating.substring(0, 2); // Truncate sequences of three or more non-spacing marks to two
            }),

        // remove leading invisible characters
        // remove over 3 repeated chars, or any repeated invisible chars
        // only allow a single trailing codepoint if it's 0xFE0E/0xFE0F and the previous char is an emoji
        // trimming to 36 chars
        cleanTrimCodePoints,
    ];

    let prevDisplayName = originalName;
    for (const step of displaySteps) {
        const result = step(prevDisplayName);
        if (!result.length) {
            const prevHex = hexInvalidString(prevDisplayName);
            return {
                displayName: `${EMPTY_SET}${prevHex.join(' ').toUpperCase()}`,
                displayNameEmpty: true,
                pureName: prevHex.join(''),
                pureNameEmpty: true,
            };
        } else {
            prevDisplayName = result;
        }
    }
    const displayName = prevDisplayName;

    const pureSteps: TransformStep[] = [
        //convert characters to their canonical form for consistent comparison
        (x) => x.normalize('NFKC'),

        //remove non-letter, non-number
        (x) => x.replace(/[^\p{Letter}\p{Number}]/gu, ''),

        //lowercase
        (x) => x.toLocaleLowerCase(),
    ];

    let prevPureName = prevDisplayName;
    for (const step of pureSteps) {
        const result = step(prevPureName);
        if (!result.length) {
            const prevHex = hexInvalidString(prevPureName);
            return {
                displayName,
                displayNameEmpty: false,
                pureName: prevHex.join(''),
                pureNameEmpty: true,
            };
        } else {
            prevPureName = result;
        }
    }
    const pureName = prevPureName;

    return {
        displayName,
        displayNameEmpty: false,
        pureName,
        pureNameEmpty: false,
    };
};
